on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Build
      run: echo ${{ github.sha }} > Release.txt
    - name: Test
      run: cat Release.txt
    - name: Test release
      uses: ultraio/action-gh-release@testing-2
      with:
        name: 'Test release'
        tag_name: testtag
        retries: 5
        retry_interval: 5000
        delete_on_existing: true
        files: Release.txt
