on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Test release
      uses: ultraio/action-gh-release@feature/retry-options-and-remove-releases
      with:
        name: 'Test release'
